// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Ref = {};

var Children = {};

var Context = {};

var Fragment = {};

var StrictMode = {};

var Suspense = {};

var SuspenseList = {};

var Experimental = {
  SuspenseList: SuspenseList
};

var Uncurried = {};

exports.Ref = Ref;
exports.Children = Children;
exports.Context = Context;
exports.Fragment = Fragment;
exports.StrictMode = StrictMode;
exports.Suspense = Suspense;
exports.Experimental = Experimental;
exports.Uncurried = Uncurried;
/* No side effect */
