// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React_V3 from "./React_V3.bs.js";
import * as ReactDOM_V3 from "./ReactDOM_V3.bs.js";
import * as ReactEvent_V3 from "./ReactEvent_V3.bs.js";
import * as ReactDOMStyle_V3 from "./ReactDOMStyle_V3.bs.js";

let React = React_V3;

let ReactDOM = ReactDOM_V3;

let ReactDOMStyle = ReactDOMStyle_V3;

let ReactEvent = ReactEvent_V3;

export {
  React,
  ReactDOM,
  ReactDOMStyle,
  ReactEvent,
}
/* No side effect */
