// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Experimental = {};

var Ref = {};

var Props = {};

var Style;

exports.Experimental = Experimental;
exports.Ref = Ref;
exports.Props = Props;
exports.Style = Style;
/* No side effect */
