// Generated by ReScript, PLEASE EDIT WITH CARE


let Synthetic = {};

let Clipboard = {};

let Composition = {};

let Keyboard = {};

let Focus = {};

let Form = {};

let Mouse = {};

let Pointer = {};

let Selection = {};

let Touch = {};

let UI = {};

let Wheel = {};

let Media = {};

let Image = {};

let Animation = {};

let Transition = {};

export {
  Synthetic,
  Clipboard,
  Composition,
  Keyboard,
  Focus,
  Form,
  Mouse,
  Pointer,
  Selection,
  Touch,
  UI,
  Wheel,
  Media,
  Image,
  Animation,
  Transition,
}
/* No side effect */
