// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React_V3 = require("./React_V3.bs.js");
var ReactDOM_V3 = require("./ReactDOM_V3.bs.js");
var ReactEvent_V3 = require("./ReactEvent_V3.bs.js");
var ReactDOMStyle_V3 = require("./ReactDOMStyle_V3.bs.js");

var React = React_V3;

var ReactDOM = ReactDOM_V3;

var ReactDOMStyle = ReactDOMStyle_V3;

var ReactEvent = ReactEvent_V3;

exports.React = React;
exports.ReactDOM = ReactDOM;
exports.ReactDOMStyle = ReactDOMStyle;
exports.ReactEvent = ReactEvent;
/* No side effect */
