// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsxRuntime = require("react/jsx-runtime");

var Root = {};

var Client = {
  Root: Root
};

var Ref = {};

var Props = {};

function jsx(key, element, props) {
  if (key !== undefined) {
    return JsxRuntime.jsx(element, props, key);
  } else {
    return JsxRuntime.jsx(element, props);
  }
}

function jsxs(key, element, props) {
  if (key !== undefined) {
    return JsxRuntime.jsxs(element, props, key);
  } else {
    return JsxRuntime.jsxs(element, props);
  }
}

var Style;

exports.Client = Client;
exports.Ref = Ref;
exports.Props = Props;
exports.jsx = jsx;
exports.jsxs = jsxs;
exports.Style = Style;
/* react/jsx-runtime Not a pure module */
