// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Root = {};

var Client = {
  Root: Root
};

var Ref = {};

var Props = {};

var Style;

exports.Client = Client;
exports.Ref = Ref;
exports.Props = Props;
exports.Style = Style;
/* No side effect */
