// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");
var JsxRuntime = require("react/jsx-runtime");

function component(prim) {
  return prim;
}

function createElementWithKey(key, component, props) {
  return React.createElement(component, key !== undefined ? Object.assign(props, {
                    key: key
                  }) : props);
}

function createElementVariadicWithKey(key, component, props, elements) {
  return Caml_splice_call.spliceApply(React.createElement, [
              component,
              key !== undefined ? Object.assign(props, {
                      key: key
                    }) : props,
              elements
            ]);
}

function jsxWithKey(key, component, props) {
  if (key !== undefined) {
    return JsxRuntime.jsx(component, props, key);
  } else {
    return JsxRuntime.jsx(component, props);
  }
}

function jsxsWithKey(key, component, props) {
  if (key !== undefined) {
    return JsxRuntime.jsxs(component, props, key);
  } else {
    return JsxRuntime.jsxs(component, props);
  }
}

var Ref = {};

var Children = {};

var Context = {};

var Fragment = {};

var StrictMode = {};

var Suspense = {};

var SuspenseList = {};

var Experimental = {
  SuspenseList: SuspenseList
};

var Uncurried = {};

exports.component = component;
exports.createElementWithKey = createElementWithKey;
exports.createElementVariadicWithKey = createElementVariadicWithKey;
exports.jsxWithKey = jsxWithKey;
exports.jsxsWithKey = jsxsWithKey;
exports.Ref = Ref;
exports.Children = Children;
exports.Context = Context;
exports.Fragment = Fragment;
exports.StrictMode = StrictMode;
exports.Suspense = Suspense;
exports.Experimental = Experimental;
exports.Uncurried = Uncurried;
/* react Not a pure module */
