// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var Children = {};

var Context = {};

var Fragment = {};

var StrictMode = {};

var Suspense = {};

function lazy_(load) {
  return React.lazy(async function () {
              return {
                      default: await load()
                    };
            });
}

var Uncurried = {};

var Usable = {};

exports.Children = Children;
exports.Context = Context;
exports.Fragment = Fragment;
exports.StrictMode = StrictMode;
exports.Suspense = Suspense;
exports.lazy_ = lazy_;
exports.Uncurried = Uncurried;
exports.Usable = Usable;
/* react Not a pure module */
