// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Client = {
  Root: Root
};

let Ref = {};

let Props = {};

let Style;

export {
  Client,
  Ref,
  Props,
  Style,
}
/* No side effect */
