// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as TestUtils from "react-dom/test-utils";

function act(func) {
  let reactFunc = () => {
    func();
  };
  TestUtils.act(reactFunc);
}

function actAsync(func) {
  return TestUtils.act(() => func());
}

function changeWithValue(element, value) {
  let event = {
    target: {
      value: value
    }
  };
  TestUtils.Simulate.change(element, event);
}

function changeWithChecked(element, value) {
  let event = {
    target: {
      checked: value
    }
  };
  TestUtils.Simulate.change(element, event);
}

let Simulate = {
  changeWithValue: changeWithValue,
  changeWithChecked: changeWithChecked
};

function findBySelector(element, selector) {
  return element.querySelector(selector);
}

function findByAllSelector(element, selector) {
  return Array.from(element.querySelectorAll(selector));
}

function findBySelectorAndTextContent(element, selector, content) {
  return Array.from(element.querySelectorAll(selector)).find(node => node.textContent === content);
}

function findBySelectorAndPartialTextContent(element, selector, content) {
  return Array.from(element.querySelectorAll(selector)).find(node => node.textContent.includes(content));
}

let DOM = {
  findBySelector: findBySelector,
  findByAllSelector: findByAllSelector,
  findBySelectorAndTextContent: findBySelectorAndTextContent,
  findBySelectorAndPartialTextContent: findBySelectorAndPartialTextContent
};

function prepareContainer(container, param) {
  let containerElement = document.createElement("div");
  let body = document.body;
  if (body !== undefined) {
    Primitive_option.valFromOption(body).appendChild(containerElement);
  }
  container.contents = Primitive_option.some(containerElement);
}

function cleanupContainer(container, param) {
  let contents = container.contents;
  if (contents !== undefined) {
    Primitive_option.valFromOption(contents).remove();
  }
  container.contents = undefined;
}

function getContainer(container) {
  let contents = container.contents;
  if (contents !== undefined) {
    return Primitive_option.valFromOption(contents);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

export {
  act,
  actAsync,
  Simulate,
  DOM,
  prepareContainer,
  cleanupContainer,
  getContainer,
}
/* react-dom/test-utils Not a pure module */
