// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

let Ref = {};

let Children = {};

let Context = {};

let Fragment = {};

let StrictMode = {};

let Suspense = {};

function lazy_(load) {
  return React.lazy(async () => ({
    default: await load()
  }));
}

let Uncurried = {};

export {
  Ref,
  Children,
  Context,
  Fragment,
  StrictMode,
  Suspense,
  lazy_,
  Uncurried,
}
/* react Not a pure module */
