// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

let noOp = (function (_x) {});

let reactComponentClass = React.Component;

noOp(reactComponentClass);

var ErrorBoundary = (function (Component) {
  function ErrorBoundary(props) {
    Component.call(this);
    this.state = { error: undefined };
  }
  ErrorBoundary.prototype = Object.create(Component.prototype);
  ErrorBoundary.prototype.componentDidCatch = function (error, info) {
    this.setState({ error: { error: error, info: info } });
  };
  ErrorBoundary.prototype.render = function () {
    return this.state.error != undefined
      ? this.props.fallback(this.state.error)
      : this.props.children;
  };
  return ErrorBoundary;
})(reactComponentClass);
;

let make = ErrorBoundary;

export {
  make,
}
/* reactComponentClass Not a pure module */
